services:
  - type: web
    name: elite-2d
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
